version: '3.8'
services:

  urls-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - urls-db

  urls-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432